- hosts: all
  remote_user: "{{ user }}"
  vars:
    - hostname: "website"
    - timezone: "America/New_York"
    - should_reboot: false        
  gather_facts: true
  become: true
  roles:
    - role: nginxinc.nginx
    - role: chusiang.php7
    - role: arillso.motd
    - role: geerlingguy.firewall
    - role: oefenweb.fail2ban
    - role: softasap.sa-secure-audit-rkhunter
    - role: reallyenglish.logrotate    
    - role: GROG.reboot
  tasks:            
    - name: change hostname to myserver
      hostname:
        name: "{{ hostname }}"  
    - name: Copy ISSUE
      copy:
        src: resources/issue
        dest: /etc/issue
        owner: root
        group: root
        mode: 0644    
  post_tasks:
    - name: Copy original website to remote host
      copy:
        src: ../src/default/
        dest: /usr/share/nginx/html
        owner: root
        group: root
        mode: 0755
    - name: Copy vulnerable files to remote host
      copy:
        src: ../src/{{ site }}/
        dest: /usr/share/nginx/html
        owner: root
        group: root
        mode: 0755
    - name: Copy explicit nginx + php configuration
      template:
        src: resources/nginx.conf.j2
        dest: /etc/nginx/conf.d/default.conf
        owner: root
        group: root
        mode: 0644
    - name: Copy PHP Info file
      template:
        src: resources/info.php.j2
        dest: /usr/share/nginx/html/info.php
        owner: root
        group: root
        mode: 0644              
    - name: Remove build-essential package
      apt:
        name: build-essential
        state: absent    
    - name: Remove git package
      apt:
        name: git
        state: absent   
    - name: Remove ftp package
      apt:
        name: ftp
        state: absent                 
    - name: Roate wtmp
      logrotate:
        name: wtmp
        files:
        - /var/log/wtmp
        frequency: monthly
        missingok: yes
        create: 0664 root utmp
        rotate: 1
        su: root syslog
        state: present
    - name: Rotate btmp
      logrotate:
        name: btmp
        files:
        - /var/log/btmp
        missingok: yes
        frequency: monthly
        create: 0660 root utmp
        rotate: 1
        su: root syslog
        state: present
    - name: Rotate apt
      logrotate:
        name: apt
        files:
        - /var/log/apt/term.log
        - /var/log/apt/history.log
        rotate: 12
        frequency: monthly
        compress: yes
        missingok: yes
        notifempty: yes
        state: present
    - name: Rotate dpkg
      logrotate: 
        name: dpkg
        files:
        - /var/log/dpkg.log
        - /var/log/alternatives.log
        frequency: monthly
        rotate: 12
        compress: yes
        delaycompress: yes
        missingok: yes
        notifempty: yes
        create: 644 root root
        su: root syslog
        state: present
    - name: Create rsyslog
      logrotate:
        name: rsyslog
        files:
        - /var/log/syslog
        rotate: 7
        frequency: daily
        missingok: yes
        notifempty: yes
        delaycompress: yes
        compress: yes
        su: root syslog
        sharedscripts: no
        postrotate:
        - "reload rsyslog >/dev/null 2>&1 || true"
        state: present
    - name: Rotate other rsyslog logs
      logrotate:
        name: rsyslog_others
        files:
          - /var/log/mail.info
          - /var/log/mail.warn
          - /var/log/mail.err
          - /var/log/mail.log
          - /var/log/daemon.log
          - /var/log/kern.log
          - /var/log/auth.log
          - /var/log/user.log
          - /var/log/lpr.log
          - /var/log/cron.log
          - /var/log/debug
          - /var/log/messages
          - /var/log/rkhunter.log
        rotate: 4
        frequency: weekly
        missingok: yes
        notifempty: yes
        compress: yes
        delaycompress: yes
        su: root syslog
        sharedscripts: yes
        postrotate:
          - "reload rsyslog >/dev/null 2>&1 || true"
        state: present
    - name: Rotate unattended-upgrades-shutdown.log
      logrotate:
        name: unattended-upgrades
        files:
          - /var/log/unattended-upgrades/unattended-upgrades.log
          - /var/log/unattended-upgrades/unattended-upgrades-shutdown.log
        rotate: 6
        frequency: monthly
        compress: yes
        missingok: yes
        notifempty: yes
        state: present
    - name: Rotate upstart
      logrotate:
        name: upstart
        files:
          - /var/log/upstart/*.log
        frequency: daily
        missingok: yes
        rotate: 7
        compress: yes
        notifempty: yes
        nocreate: yes
        state: present
    - name: Rotate audit
      logrotate:
        name: audit
        files:
          - /var/log/audit/*.log
        frequency: daily
        missingok: yes
        rotate: 7
        compress: yes
        notifempty: yes
        nocreate: yes
        state: present
    - name: update www-data group membership
      user:
        name: nginx
        groups: www-data
        append: yes             
    - name: Deliberately allow php exec - DANGER WILL ROBINSON
      replace:
        path: /etc/php/7.1/fpm/php.ini
        regexp: 'disable_functions = exec,passthru,shell_exec,system,proc_open,popen'
        replace: '; disable_functions = exec,passthru,shell_exec,system,proc_open,popen'        
    - name: Make nginx HTML dir write-able for webshell file upload
      file:
        path: /usr/share/nginx/html
        owner: root
        group: www-data
        mode: '0775'        
    - name: Restart Nginx service
      systemd:
        name: nginx
        state: restarted
        daemon_reload: yes                
    - name: Cleanup unused packages
      apt:
          autoremove: yes
    - name: reboot to finalize prep
      include_role:
          name: GROG.reboot
    

          