- hosts: win-blue-frenemy
  gather_facts: no

  tasks:
    - name: Remove directory structure
      win_file:
        path: C:\\Users\\admin\\Desktop\\googlebot
        state: absent

    - name: Store file
      win_copy:
        src: "./resources/googlebot.exe"
        dest: "c:\\Users\\admin1\\Desktop\\"

    - name: run googlebot
      win_shell: cd c:\Users\admin1\Desktop\ ; .\googlebot.exe

    - name: Ensure user bob is present
      win_user:
        name: admin
        password:
        state: present
        groups:
          - Users

    - name: Join Domain
      win_domain_membership:
        dns_domain_name: user.frenemydpw.com
        # hostname: blue-w10-20
        domain_admin_user: Administrator@user.frenemydpw.com
        domain_admin_password: Password1!
        state: domain
      register: domain_state

    - name: Join Workgroup
      win_domain_membership:
        workgroup_name: BLUEWIN
        domain_admin_user: Administrator@user.frenemydpw.com
        domain_admin_password: Password1!
        state: workgroup
      register: domain_state

    - name: Reboot
      win_reboot:
      when: domain_state.reboot_required
