# setup gitlab http server
- hosts: test
  remote_user: dj
  gather_facts: true
  become: true
  tasks:
    - name: Run gitlab setup script
      shell: sudo apt-get update && \
        sudo apt-get install -y curl openssh-server ca-certificates tzdata perl && \
        sudo curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.deb.sh | sudo bash && \
        sudo EXTERNAL_URL="https://gitlab.example.com" apt-get install gitlab-ee && \
        sudo cat > /etc/gitlab/initial_root_password /home/$USER/gitlab_pw
